"""
PDF Parser — extracts structured data from a previously generated report.

Strategy:
  1. Use PyMuPDF (fitz) to extract all text from the PDF.
  2. Locate section headings (e.g. "1. Informacje Ogólne") and parse
     key-value pairs between headings.
  3. Return a dict matching the structure expected by each module's set_data().

This is best-effort: if the PDF was generated by this application the
extraction should be reliable; hand-edited PDFs may parse partially.
"""
import re
from datetime import date, datetime
from typing import Any

try:
    import fitz  # PyMuPDF
    FITZ_AVAILABLE = True
except ImportError:
    FITZ_AVAILABLE = False


# ── Helpers ───────────────────────────────────────────────────────────────────

def _parse_date(text: str) -> date | None:
    for fmt in ("%d.%m.%Y", "%Y-%m-%d", "%d/%m/%Y"):
        try:
            return datetime.strptime(text.strip(), fmt).date()
        except ValueError:
            continue
    return None


def _parse_dates(text: str) -> list[date]:
    """Parse comma-separated date list like '01.01.2024, 02.01.2024'."""
    parts = [p.strip() for p in text.split(",")]
    result = []
    for p in parts:
        d = _parse_date(p)
        if d:
            result.append(d)
    return result


# ── Section splitter ──────────────────────────────────────────────────────────

_SECTION_RE = re.compile(
    r"^\s*(\d+)\.\s+(Informacje Ogólne|Sprzęt Pomiarowy|Czujniki Światłowodowe"
    r"|Czujniki Inne|Inwentaryzacja|Przebieg Pomiarów"
    r"|Lista Rzeczy do Zabrania|Uwagi|Logistyka i Organizacja)\s*$",
    re.MULTILINE,
)

_SECTION_NAMES = {
    "Informacje Ogólne":       1,
    "Sprzęt Pomiarowy":        2,
    "Czujniki Światłowodowe":  3,
    "Czujniki Inne":           4,
    "Inwentaryzacja":          5,
    "Przebieg Pomiarów":       6,
    "Lista Rzeczy do Zabrania": 7,
    "Uwagi":                   8,
    "Logistyka i Organizacja": 9,
}


def _split_sections(full_text: str) -> dict[int, str]:
    """Split extracted text into per-module blobs."""
    matches = list(_SECTION_RE.finditer(full_text))
    sections: dict[int, str] = {}
    for i, m in enumerate(matches):
        mid = int(m.group(1))
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(full_text)
        sections[mid] = full_text[start:end].strip()
    return sections


# ── KV extraction ─────────────────────────────────────────────────────────────

def _extract_kv(text: str) -> dict[str, str]:
    """
    Very simple KV extractor: looks for lines of the form
      Label\nValue  or  Label: Value
    Returns a lowercased-key dict.
    """
    result: dict[str, str] = {}
    lines = [l.strip() for l in text.splitlines() if l.strip()]

    # Try "Label: Value" format first
    for line in lines:
        if ":" in line:
            k, _, v = line.partition(":")
            k = k.strip().lower()
            v = v.strip()
            if k and v:
                result[k] = v

    # Also try adjacent-line format (label on one line, value on next)
    i = 0
    while i < len(lines) - 1:
        candidate_label = lines[i]
        candidate_value = lines[i + 1]
        # If label looks like a known field name (short, no digits)
        if len(candidate_label) < 40 and not re.search(r"\d{2}\.\d{2}\.\d{4}", candidate_label):
            key = candidate_label.lower().rstrip(":")
            if key not in result:
                result[key] = candidate_value
        i += 1

    return result


# ── Per-module parsers ────────────────────────────────────────────────────────

def _parse_module1(text: str) -> dict:
    kv = _extract_kv(text)

    # Dates
    dates_raw = kv.get("data pomiarów", kv.get("daty pomiarów", ""))
    dates = _parse_dates(dates_raw) if dates_raw else []

    report_date_raw = kv.get("data wypełnienia", "")
    report_date = _parse_date(report_date_raw)

    return {
        "project_number": kv.get("numer projektu", ""),
        "project_name":   kv.get("nazwa projektu", ""),
        "initials":       kv.get("inicjały", kv.get("inicjały wypełniającego", "")),
        "report_date":    report_date,
        "location":       kv.get("lokalizacja", ""),
        "maps_link":      kv.get("google maps", ""),
        "measurement_dates": dates,
        "team_leader":    kv.get("kierownik pomiarów", ""),
        "team_members":   kv.get("skład zespołu", ""),
        "contact_title":  "",
        "contact_first":  "",
        "contact_last":   kv.get("osoba do kontaktu", ""),
        "contact_phone":  kv.get("telefon", ""),
        "contact_email":  kv.get("e-mail", kv.get("email", "")),
    }


def _parse_module2(text: str) -> dict:
    lines = [l.strip() for l in text.splitlines() if l.strip() and l.startswith("•")]
    items = [l.lstrip("• ").strip() for l in lines]

    # Split roughly: optical vs other — we can't perfectly recover this from PDF text
    # so we put everything in "custom" for the other_devices group
    return {
        "optical_recorders": {"checked": [], "custom": items[:len(items)//2 + 1]},
        "other_devices":     {"checked": [], "custom": items[len(items)//2 + 1:]},
    }


def _parse_sensor_list(text: str) -> list[dict]:
    """Parse a table-like sensor list from raw text."""
    sensors = []
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    # Skip header line
    for line in lines[1:]:
        parts = line.split()
        if len(parts) >= 2:
            sensors.append({
                "name":   parts[0] if len(parts) > 0 else "",
                "serial": parts[1] if len(parts) > 1 else "",
                "notes":  " ".join(parts[2:]) if len(parts) > 2 else "",
                "image_path": "",
            })
    return sensors


def _parse_module5(text: str) -> dict:
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    if not lines:
        return {}
    # First line = headers (tab or multi-space separated)
    headers_raw = re.split(r"\s{2,}|\t", lines[0])
    rows = []
    for line in lines[1:]:
        cells = re.split(r"\s{2,}|\t", line)
        rows.append(cells)
    return {"headers": headers_raw, "rows": rows, "description": "", "image_path": ""}


def _parse_module6(text: str) -> dict:
    desc = text[:text.find("Harmonogram")] if "Harmonogram" in text else text
    return {
        "description": desc.strip(),
        "desc_images": [],
        "schedule":    [],
        "problems":    "",
        "prob_images": [],
    }


def _parse_module7(text: str) -> dict:
    lines = [l.strip().lstrip("• ") for l in text.splitlines() if l.strip()]
    return {"items": lines}


def _parse_module8(text: str) -> dict:
    return {"notes": text.strip(), "images": []}


def _parse_module9(text: str) -> dict:
    kv = _extract_kv(text)
    return {
        "parking":       kv.get("parkowanie", ""),
        "site_location": kv.get("lokalizacja pomiarów", ""),
        "accommodation": kv.get("nocleg", ""),
        "other":         kv.get("inne", ""),
    }


_MODULE_PARSERS = {
    1: _parse_module1,
    2: _parse_module2,
    3: lambda t: {"sensors": _parse_sensor_list(t)},
    4: lambda t: {"sensors": _parse_sensor_list(t)},
    5: _parse_module5,
    6: _parse_module6,
    7: _parse_module7,
    8: _parse_module8,
    9: _parse_module9,
}


# ── Public API ────────────────────────────────────────────────────────────────

def parse_pdf(path: str) -> dict[int, dict]:
    """
    Parse a PDF file and return per-module data dicts.

    Returns an empty dict if PyMuPDF is not installed or the file is
    unreadable.  Partial results are returned when only some sections
    are found.
    """
    if not FITZ_AVAILABLE:
        raise ImportError(
            "PyMuPDF (fitz) is required for PDF import. "
            "Install it with: pip install PyMuPDF"
        )

    try:
        doc = fitz.open(path)
    except Exception as exc:
        raise ValueError(f"Cannot open PDF: {exc}") from exc

    full_text = "\n".join(page.get_text() for page in doc)
    doc.close()

    sections = _split_sections(full_text)
    result: dict[int, dict] = {}

    for mid, text in sections.items():
        parser = _MODULE_PARSERS.get(mid)
        if parser:
            try:
                parsed = parser(text)
                parsed["enabled"] = True
                result[mid] = parsed
            except Exception:
                # Best-effort: skip modules that fail to parse
                pass

    # Module 1 is always enabled
    if 1 in result:
        result[1]["enabled"] = True

    return result
